# DEV Compose file.
# For a production file see: README.md

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  app:
    # build: .
    image: cupcakearmy/cryptgeon
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 10 MiB
    ports:
      - 1234:5000
